### ISSUE TITLE
Example does not work without https

### ISSUE THREAD

**Issue by Saturate** [jasonpecor/DecibelMeter#2]
Example should use HTTPS for this to work in newer chrome versions.

> getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by jasonpecor** [comment]
Thanks.  I'll move the example to a secure server.

**Comment by jasonpecor** [comment]
Example moved to secure server, however Audio API has changed significantly, so example will not work on modern browsers.  Rewrite is in progress.
