### ISSUE TITLE
Example is not working in Chrome Andorid

### ISSUE THREAD

**Issue by quedicesebas** [jasonpecor/DecibelMeter#3]
I got this:

jasonpecor.com says:

Error connecting to source

**Comment by jasonpecor** [comment]
Chromium has deprecated support on non-secure sources; I need to move the example to a secure (HTTPS) server.  It looks like MediaStreamTrack.getSources() has also been deprecated.  I'll need to create a new release to fix this as well.

**Comment by quedicesebas** [comment]
It would be possible to use this in a cordova app?

**Comment by jasonpecor** [comment]
My understanding is that Cordova wraps your code in a native web view, so you would have to check the feature support of the web view for your target platform.

**Comment by pahaz** [comment]
Same problem for Chrome 52.0 =/

```
MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details.
decibel-meter.js:99 

getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
http://jasonpecor.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
4decibel-meter.js:185 

Uncaught Error: DecibelMeter: Not connected to source
```

**Comment by jasonpecor** [comment]
Example has been moved to a secure server.  The Audio API has changed significantly.  A new version supporting these changes is in the works.

**Comment by UInt2048** [comment]
@jasonpecor How has the new version been going? #9 seems to be stopping usage of this version...
